/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoswing.presentacion;

/**
 *
 * @author angul
 */
import java.io.File;
import javax.swing.JFileChooser;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectoswing.modelo.Estudiante;
import proyectoswing.negocio.EstudianteNegocio;
import proyectoswing.excepciones.DatoInvalidoException;
import proyectoswing.excepciones.RegistroDuplicadoException;
public class EstudiantePanel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EstudiantePanel.class.getName());
    
    private EstudianteNegocio estudianteNegocio;

    /**
     * Creates new form EstudiantePanel
     */
    public EstudiantePanel() {
        initComponents();
        estudianteNegocio = new EstudianteNegocio();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbCarrera = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbBuscarPor = new javax.swing.JComboBox<>();
        btnRefrescar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        chkActivo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("Nombre");

        jLabel3.setText("Edad");

        jLabel4.setText("Carrera");

        cmbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ing Sistemas", "Educacion", "Veterinaria", "Admin Empresas" }));

        jLabel5.setText("Correo");

        jLabel6.setText("Telefono");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        jLabel7.setText("Observaciones");

        jTable1.setBackground(new java.awt.Color(0, 153, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Edad", "Carrera", "Genero", "Estado", "Correo", "Telefono"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        txtBuscar.addActionListener(this::txtBuscarActionPerformed);

        jLabel8.setText("BUSQUEDA POR NOMBRE O CARRERA");

        cmbBuscarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ing Sistemas", "Educacion", "Veterinaria", "Admin Empresas" }));
        cmbBuscarPor.addActionListener(this::cmbBuscarPorActionPerformed);

        btnRefrescar.setText("REFRESCAR");
        btnRefrescar.addActionListener(this::btnRefrescarActionPerformed);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnExportar.setText("Exportar");
        btnExportar.addActionListener(this::btnExportarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        rbMasculino.setText("Masculino");

        rbFemenino.setText("Femenino");

        chkActivo.setText("Activo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(64, 64, 64)
                                    .addComponent(txtID))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(29, 29, 29)
                                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbFemenino)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(rbMasculino)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkActivo))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(36, 36, 36)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmbCarrera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCorreo)
                                        .addComponent(txtTelefono))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEliminar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnExportar)))
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditar)
                            .addComponent(btnLimpiar))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btnRefrescar)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(btnRefrescar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbMasculino)
                            .addComponent(chkActivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbFemenino)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEditar)
                            .addComponent(btnExportar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminar)
                            .addComponent(btnLimpiar))
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnGuardar)
                        .addGap(78, 78, 78))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean modoEdicion = false;
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {

            Estudiante estudiante = new Estudiante();

            estudiante.setId(Integer.parseInt(txtID.getText().trim()));
            estudiante.setNombre(txtNombre.getText().trim());
            estudiante.setEdad(Integer.parseInt(txtEdad.getText().trim()));
            estudiante.setCarrera(cmbCarrera.getSelectedItem().toString());

            // Género
            if (rbMasculino.isSelected()) {
                estudiante.setGenero("Masculino");
            } else if (rbFemenino.isSelected()) {
                estudiante.setGenero("Femenino");
            } else {
                estudiante.setGenero("");
            }

            estudiante.setActivo(chkActivo.isSelected());
            estudiante.setCorreo(txtCorreo.getText().trim());
            estudiante.setTelefono(txtTelefono.getText().trim());
            estudiante.setObservaciones(txtObservaciones.getText().trim());

            if (modoEdicion) {

                estudianteNegocio.editar(estudiante);

                JOptionPane.showMessageDialog(
                        this,
                        "Estudiante actualizado correctamente."
                );

                modoEdicion = false;

            } else {

                estudianteNegocio.registrar(estudiante);

                JOptionPane.showMessageDialog(
                        this,
                        "Estudiante registrado correctamente."
                );
            }

            limpiarCampos();
            cargarTabla();

        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(
                    this,
                    "El ID y la edad deben ser valores numéricos."
            );

        } catch (DatoInvalidoException | RegistroDuplicadoException ex) {

            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage()
            );
            }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        txtID.setText("");
        txtNombre.setText("");
        txtEdad.setText("");
        txtCorreo.setText("");
        txtTelefono.setText("");
        txtObservaciones.setText("");

        cmbCarrera.setSelectedIndex(0);

        

        chkActivo.setSelected(false);
   
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un estudiante de la tabla."
            );
            return;
        }

        txtID.setText(jTable1.getValueAt(fila, 0).toString());
        txtNombre.setText(jTable1.getValueAt(fila, 1).toString());
        txtEdad.setText(jTable1.getValueAt(fila, 2).toString());
        cmbCarrera.setSelectedItem(jTable1.getValueAt(fila, 3).toString());

        String genero = jTable1.getValueAt(fila, 4).toString();
        if (genero.equalsIgnoreCase("Masculino")) {
            rbMasculino.setSelected(true);
        } else {
            rbFemenino.setSelected(true);
        }
        modoEdicion = true;

        chkActivo.setSelected(
                jTable1.getValueAt(fila, 5).toString().equalsIgnoreCase("Sí")
        );

        txtCorreo.setText(jTable1.getValueAt(fila, 6).toString());
        txtTelefono.setText(jTable1.getValueAt(fila, 7).toString());
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         if (txtID.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Seleccione un estudiante para eliminar."
        );
        return;
    }

    // Confirmar la eliminación
    int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de que desea eliminar este estudiante?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (opcion == JOptionPane.YES_OPTION) {

        try {
            int id = Integer.parseInt(txtID.getText());

            estudianteNegocio.eliminar(id);

            JOptionPane.showMessageDialog(
                    this,
                    "Estudiante eliminado correctamente."
            );

            limpiarCampos();
            cargarTabla();

            // Volver al modo de registro
            modoEdicion = false;

        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(
                    this,
                    "El ID no es válido."
            );
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
        JFileChooser selector = new JFileChooser();
        selector.setDialogTitle("Guardar archivo CSV");

        int opcion = selector.showSaveDialog(this);

        if (opcion == JFileChooser.APPROVE_OPTION) {

            try {

                File archivo = selector.getSelectedFile();

                // Si no escribe la extensión, se agrega automáticamente
                String ruta = archivo.getAbsolutePath();

                if (!ruta.toLowerCase().endsWith(".csv")) {
                    ruta += ".csv";
                }

                estudianteNegocio.exportarCSV(ruta);

                JOptionPane.showMessageDialog(
                        this,
                        "Archivo exportado correctamente."
                );

            } catch (Exception ex) {

                JOptionPane.showMessageDialog(
                        this,
                        "Error al exportar: " + ex.getMessage()
                );
            }
        }
    }//GEN-LAST:event_btnExportarActionPerformed

    private void cmbBuscarPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBuscarPorActionPerformed
        // TODO add your handling code here:
        String carrera = cmbBuscarPor.getSelectedItem().toString();

        DefaultTableModel modelo
                = (DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0);

        List<Estudiante> lista
                = estudianteNegocio.buscarPorCarrera(carrera);

        for (Estudiante e : lista) {

            modelo.addRow(new Object[]{
                e.getId(),
                e.getNombre(),
                e.getEdad(),
                e.getCarrera(),
                e.getGenero(),
                e.isActivo() ? "Sí" : "No",
                e.getCorreo(),
                e.getTelefono()
            });
        }
    }//GEN-LAST:event_cmbBuscarPorActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo
                = (DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0);

        String nombre = txtBuscar.getText();

        List<Estudiante> lista
                = estudianteNegocio.buscarPorNombre(nombre);

        for (Estudiante e : lista) {

            modelo.addRow(new Object[]{
                e.getId(),
                e.getNombre(),
                e.getEdad(),
                e.getCarrera(),
                e.getGenero(),
                e.isActivo() ? "Sí" : "No",
                e.getCorreo(),
                e.getTelefono()
            });
        }
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        // TODO add your handling code here:
        

        // Limpia el cuadro de búsqueda
        txtBuscar.setText("");

        // Opcional: restablecer el ComboBox de búsqueda
        cmbBuscarPor.setSelectedIndex(0);
        
        cargarTabla();
    }//GEN-LAST:event_btnRefrescarActionPerformed

        
        
    

    private void limpiarCampos() {
        txtID.setText("");
        txtNombre.setText("");
        txtEdad.setText("");
        txtCorreo.setText("");
        txtTelefono.setText("");
        txtObservaciones.setText("");

        cmbCarrera.setSelectedIndex(0);
        
        chkActivo.setSelected(false);
    }

    private void buscar() {

        DefaultTableModel modelo
                = (DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0);

        List<Estudiante> lista;

        String texto = txtBuscar.getText().trim();
        String opcion = cmbBuscarPor.getSelectedItem().toString();

        if (opcion.equals("Nombre")) {

            lista = estudianteNegocio.buscarPorNombre(texto);

        } else if (opcion.equals("Carrera")) {

            lista = estudianteNegocio.buscarPorCarrera(texto);

        } else { // Estado

            boolean activo = texto.equalsIgnoreCase("Activo")
                    || texto.equalsIgnoreCase("Sí")
                    || texto.equalsIgnoreCase("Si")
                    || texto.equalsIgnoreCase("true");

            lista = estudianteNegocio.buscarPorEstado(activo);
        }

        for (Estudiante e : lista) {

            modelo.addRow(new Object[]{
                e.getId(),
                e.getNombre(),
                e.getEdad(),
                e.getCarrera(),
                e.getGenero(),
                e.isActivo() ? "Sí" : "No",
                e.getCorreo(),
                e.getTelefono()
            });
        }
    }

    private void cargarTabla() {

        DefaultTableModel modelo
                = (DefaultTableModel) jTable1.getModel();

        // Limpiar la tabla
        modelo.setRowCount(0);

        // Recorrer todos los estudiantes
        for (Estudiante estudiante : estudianteNegocio.obtenerTodos()) {

            modelo.addRow(new Object[]{
                estudiante.getId(),
                estudiante.getNombre(),
                estudiante.getEdad(),
                estudiante.getCarrera(),
                estudiante.getGenero(),
                estudiante.isActivo() ? "Sí" : "No",
                estudiante.getCorreo(),
                estudiante.getTelefono()
            });
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EstudiantePanel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkActivo;
    private javax.swing.JComboBox<String> cmbBuscarPor;
    private javax.swing.JComboBox<String> cmbCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
